Add Procfile
spartansystems/spartan-composer-recipes pull request #28
Opened 2017-02-17 23:49 UTC by Mrjaco12

Why:

* Heroku will want it to run our app

This change addresses the need by:

* Adding a simple default procfile
* Adding a recipe for installing it

2017-02-19 17:49 UTC, samcdavid commented
Does this cover installing `foreman` in the development group? I don't think that we have required that in the past. However, it wouldn't be a bad idea.

2017-02-19 18:35 UTC, Mrjaco12 commented
It does not. We need this config to tell heroku how to run the app. We aren't planning on having Foreman run locally by default at this point.

2017-03-03 14:34 UTC, squaresurf requested changes

2017-03-03 14:34 UTC, squaresurf commented on recipes/foreman.rb
> +description: "Add the default Foreman Procfile"
These lines are probably why @samcdavid thought this was for Foreman. Should we change them to Heroku? Not to mention the recipe filename.

2017-03-03 14:40 UTC, Mrjaco12 commented on recipes/foreman.rb
> +description: "Add the default Foreman Procfile"
Any recommendation on a new name? Procfile? It is for Foreman. Just not local Foreman lol.

2017-03-03 14:46 UTC, squaresurf approved these changes

2017-03-03 14:46 UTC, merged

2017-03-03 16:53 UTC, Mrjaco12 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rails Auth Flow](https://trello.com/c/9M0vleig/643-rails-auth-flow)